version: '2'
services:
 backend:
  build: ./backend/
  ports:
   - "4000:4000"
  volumes:
   - ./backend:/usr/src/app
  depends_on:
   - mysql
 frontend:
  build: ./frontend/
  ports:
   - "3000:3000"
  volumes:
    - ./frontend:/usr/src/app
  depends_on:
   - backend
 mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  container_name: letitgo-mysql
  environment:
   MYSQL_ROOT_PASSWORD: 123456
   MYSQL_DATABASE: letitgo